PRAGMA foreign_keys = OFF;
DELETE FROM graph_edges;
DELETE FROM corpus_chunks;
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-bda-sec2-c', 'The Biological Diversity Act, 2002 (Act No. 18 of 2003)', 'Section 2(c)', 'Section 2(c) - Definition of Biological Resources', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2046', '''biological resources'' means plants, animals and micro-organisms or parts thereof, their genetic material and by-products (excluding value added products) with actual or potential use or value, but does not include human genetic material. The 2023 amendment explicitly exempted registered AYUSH practitioners and codified traditional knowledge holders from certain notification requirements for internal clinical use, but commercial utilization and foreign patenting remain strictly regulated under NBA oversight.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-bda-sec3', 'The Biological Diversity Act, 2002', 'Section 3', 'Section 3 - Certain Persons Not to Undertake Biodiversity-related Activities without NBA Approval', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2046', 'No person who is not a citizen of India, or a citizen of India who is an NRI, or a body corporate, association or organization not incorporated or registered in India, or incorporated in India which has any non-Indian participation in its share capital or management, shall obtain any biological resource occurring in India or knowledge associated thereto for research or for commercial utilization or for bio-survey and bio-utilization without previous approval of the National Biodiversity Authority (Form I).');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-bda-sec6', 'The Biological Diversity Act, 2002', 'Section 6', 'Section 6 - Prior Approval of NBA Required for Applying for Intellectual Property Rights', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2046', '(1) No person shall apply for any intellectual property right, by whatever name called, in or outside India for any invention based on any research or information on a biological resource obtained from India without obtaining the previous approval of the National Biodiversity Authority before making such application. Provided that if a person applies for a patent, permission of the National Biodiversity Authority may be obtained after making the application but before the grant of the patent by the patent authority. (2) The National Biodiversity Authority may, while granting the approval under this section, impose benefit sharing fee or royalty or both or conditions on the commercial utilization of such patent.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-bda-sec7', 'The Biological Diversity Act, 2002', 'Section 7', 'Section 7 - Prior Intimation to State Biodiversity Board (SBB) by Indian Citizens for Commercial Utilization', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2046', 'No person, who is a citizen of India or a body corporate, association or organization which is registered in India, shall obtain any biological resource for commercial utilization, or bio-survey and bio-utilization for commercial utilization except after giving prior intimation to the State Biodiversity Board concerned. Vaids and hakims who are practicing Indian systems of medicine are exempted from giving prior intimation.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-bda-sec21', 'The Biological Diversity Act, 2002', 'Section 21', 'Section 21 - Determination of Equitable Benefit Sharing by National Biodiversity Authority', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2046', 'The National Biodiversity Authority shall ensure that the terms and conditions subject to which approval is granted secures equitable sharing of benefits arising out of the use of accessed biological resources, their by-products, innovations and practices associated with their use and applications and knowledge relating thereto in accordance with mutually agreed terms and conditions between the persons applying for such approval, local bodies concerned and the benefit claimers. Benefit sharing mechanisms include grant of joint ownership of IPRs, transfer of technology, location of production/R&D units in source regions, association of Indian scientists/claimers, and payment of monetary compensation into the National Biodiversity Fund.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-bda-sec55', 'The Biological Diversity Act, 2002', 'Section 55', 'Section 55 - Penalties for Contravention of Section 3, Section 4 and Section 6', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2046', 'Whoever contravenes or attempts to contravene or abets the contravention of the provisions of section 3 or section 4 or section 6 shall be punishable with imprisonment for a term which may extend to five years, or with fine which may extend to ten lakh rupees and where the damage caused exceeds ten lakh rupees such fine may commensurate with the damage caused, or with both. (Amended 2023 to civil penalties adjudicated by designated adjudicating officers, with fines up to Rs. 50 lakhs).');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-chyawanprash', 'Ayurvedic Formulary of India (AFI), Part I, First Schedule DCA 1940', 'Chyawanprash', 'Chyawanprash (Avaleha) - AFI Part I (3:11)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Chyawanprash

Sanskrit / Classical Name: च्यवनप्राश

Dosage Form: Avaleha (Semisolid electuary)

Classical Reference / Authoritative Text: Charaka Samhita, Chikitsasthana, Adhyaya 1:1, Shloka 62-74; Sharangadhara Samhita, Madhyama Khanda, Adhyaya 8; AFI Part I, 3:11

Key Botanical & Mineral Ingredients: Phyllanthus emblica (Amalaki fresh fruit) (500 fruits), Aegle marmelos (Bilva root/bark) (1 part), Clerodendrum phlomidis (Agnimantha) (1 part), Oroxylum indicum (Shyonaka) (1 part), Stereospermum suaveolens (Patala) (1 part), Gmelina arborea (Gambhari) (1 part), Desmodium gangeticum (Shalaparni) (1 part), Uraria picta (Prishniparni) (1 part), Solanum indicum (Brihati) (1 part), Solanum surattense (Kantakari) (1 part), Tribulus terrestris (Gokshura) (1 part), Piper longum (Pippali) (1 part), Pistacia chinensis / integerrima (Karkatashringi) (1 part), Phyllanthus niruri (Bhumiamalaki) (1 part), Vitis vinifera (Draksha) (1 part), Tinospora cordifolia (Guduchi) (1 part), Inula racemosa / Terminalia chebula (Haritaki) (1 part), Sida cordifolia (Bala) (1 part), Boerhavia diffusa (Punarnava) (1 part), Adhatoda vasica (Vasa) (1 part), Withania somnifera (Ashwagandha) (1 part), Asparagus racemosus (Shatavari) (1 part), Clarified butter (Ghrita) and Sesame oil (Tila taila) (Vehicle), Sugar candy (Sharkara) and Honey (Madhu) (Sweetener)

Therapeutic Indications: K, a, s, a,  , (, C, o, u, g, h, ), ,,  , S, h, w, a, s, a,  , (, A, s, t, h, m, a,  , /,  , D, y, s, p, n, e, a, ), ,,  , K, s, h, a, y, a,  , (, W, a, s, t, i, n, g,  , d, i, s, e, a, s, e,  , /,  , P, h, t, h, i, s, i, s, ), ,,  , R, a, s, a, y, a, n, a,  , (, I, m, m, u, n, o, m, o, d, u, l, a, t, o, r,  , a, n, d,  , r, e, j, u, v, e, n, a, t, i, o, n, ), ,,  , D, a, u, r, b, a, l, y, a,  , (, G, e, n, e, r, a, l,  , d, e, b, i, l, i, t, y, ), ,,  , S, v, a, r, a, b, h, e, d, a,  , (, H, o, a, r, s, e, n, e, s, s,  , o, f,  , v, o, i, c, e, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-triphala-churna', 'Ayurvedic Formulary of India (AFI), Part I', 'Triphala Churna', 'Triphala Churna - AFI Part I (7:16)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Triphala Churna

Sanskrit / Classical Name: त्रिफला चूर्ण

Dosage Form: Churna (Fine powdered herbal mixture)

Classical Reference / Authoritative Text: Sharangadhara Samhita, Madhyama Khanda, Adhyaya 6, Shloka 12-14; Charaka Samhita, Chikitsasthana 1:3; AFI Part I, 7:16; API Part I, Vol I

Key Botanical & Mineral Ingredients: Terminalia chebula (Haritaki dried pericarp) (1 part (equal)), Terminalia bellirica (Bibhitaki dried pericarp) (1 part (equal)), Phyllanthus emblica / Emblica officinalis (Amalaki dried pericarp) (1 part (equal))

Therapeutic Indications: A, n, a, h, a,  , (, C, o, n, s, t, i, p, a, t, i, o, n,  , /,  , F, l, a, t, u, l, e, n, c, e, ), ,,  , V, i, b, a, n, d, h, a, ,,  , N, e, t, r, a, r, o, g, a,  , (, O, p, h, t, h, a, l, m, i, c,  , d, i, s, o, r, d, e, r, s, ,,  , t, a, k, e, n,  , w, i, t, h,  , h, o, n, e, y,  , a, n, d,  , g, h, e, e, ), ,,  , P, r, a, m, e, h, a,  , (, U, r, i, n, a, r, y,  , d, i, s, o, r, d, e, r, s,  , /,  , M, e, t, a, b, o, l, i, c,  , s, y, n, d, r, o, m, e, ), ,,  , D, e, e, p, a, n, a, ,,  , P, a, c, h, a, n, a, ,,  , R, a, s, a, y, a, n, a, .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-yograj-guggulu', 'Ayurvedic Formulary of India (AFI), Part I', 'Yograj Guggulu', 'Yograj Guggulu (Vati) - AFI Part I (5:7)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Yograj Guggulu

Sanskrit / Classical Name: योगराज गुग्गुलु

Dosage Form: Vati / Gutika (Pill / Tablet)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Amavata Rogadhikara, Shloka 90-95; Sharangadhara Samhita, Madhyama Khanda, Adhyaya 7; AFI Part I, 5:7

Key Botanical & Mineral Ingredients: Commiphora mukul (Shuddha Guggulu) (54 parts), Zingiber officinale (Shunthi) (1 part), Piper longum (Pippali) (1 part), Piper nigrum (Maricha) (1 part), Piper retrofractum (Chavya) (1 part), Plumbago zeylanica (Chitraka) (1 part), Ferula foetida (Hingu) (1 part), Trachyspermum ammi (Ajawain) (1 part), Carum carvi (Krishna Jeeraka) (1 part), Cuminum cyminum (Shweta Jeeraka) (1 part), Cedrus deodara (Devadaru) (1 part), Terminalia chebula (Haritaki) (1 part), Terminalia bellirica (Bibhitaki) (1 part), Phyllanthus emblica (Amalaki) (1 part), Cyperus rotundus (Musta) (1 part), Embelia ribes (Vidanga) (1 part), Tribulus terrestris (Gokshura) (1 part)

Therapeutic Indications: A, m, a, v, a, t, a,  , (, R, h, e, u, m, a, t, o, i, d,  , a, r, t, h, r, i, t, i, s, ), ,,  , S, a, n, d, h, i, g, a, t, a,  , V, a, t, a,  , (, O, s, t, e, o, a, r, t, h, r, i, t, i, s, ), ,,  , V, a, t, a, v, y, a, d, h, i,  , (, N, e, u, r, o, l, o, g, i, c, a, l,  , d, i, s, o, r, d, e, r, s, ), ,,  , K, a, t, i,  , S, h, o, o, l, a,  , (, L, u, m, b, a, g, o, ), ,,  , S, c, i, a, t, i, c, a, .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-haridra-khanda', 'Ayurvedic Formulary of India (AFI), Part I', 'Haridra Khanda', 'Haridra Khanda (Granules / Avaleha) - AFI Part I (3:31)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Haridra Khanda

Sanskrit / Classical Name: हरिद्रा खण्ड

Dosage Form: Khanda / Avaleha (Granules / Confection)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Sheetapitta Rogadhikara, Shloka 12-16; AFI Part I, 3:31; API Part I

Key Botanical & Mineral Ingredients: Curcuma longa (Haridra / Turmeric rhizome powder) (384 g), Cow''s Ghee (Go-Ghrita) (288 g), Cow''s Milk (Go-Dugdha) (3.072 kg), Sharkara (Sugar candy) (2.4 kg), Zingiber officinale (Shunthi) (48 g), Piper nigrum (Maricha) (48 g), Piper longum (Pippali) (48 g), Cinnamomum tamala (Tejapatra) (48 g), Elettaria cardamomum (Ela) (48 g), Cinnamomum zeylanicum (Twak) (48 g), Embelia ribes (Vidanga) (48 g), Operculina turpethum (Trivrit) (48 g), Triphala (Haritaki, Bibhitaki, Amalaki) (48 g each), Cyperus rotundus (Musta) (48 g), Lauha Bhasma (Incinerated Iron) (48 g)

Therapeutic Indications: S, h, e, e, t, a, p, i, t, t, a,  , (, U, r, t, i, c, a, r, i, a,  , /,  , A, l, l, e, r, g, i, c,  , r, a, s, h, ), ,,  , U, d, a, r, d, a, ,,  , K, o, t, h, a, ,,  , K, a, n, d, u,  , (, P, r, u, r, i, t, u, s, ), ,,  , A, l, l, e, r, g, i, c,  , r, h, i, n, i, t, i, s, ,,  , S, k, i, n,  , a, l, l, e, r, g, i, e, s, .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-ashwagandharishta', 'Ayurvedic Formulary of India (AFI), Part I', 'Ashwagandharishta', 'Ashwagandharishta (Asava/Arishta) - AFI Part I (1:3)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Ashwagandharishta

Sanskrit / Classical Name: अश्वगन्धारिष्ट

Dosage Form: Arishta (Self-generated hydroalcoholic fermentation)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Murcha Rogadhikara, Shloka 13-17; AFI Part I, 1:3

Key Botanical & Mineral Ingredients: Withania somnifera (Ashwagandha root) (2.4 kg), Musali (Chlorophytum tuberosum) (960 g), Manjishta (Rubia cordifolia) (480 g), Haritaki (Terminalia chebula) (480 g), Haridra (Curcuma longa) (480 g), Daru Haridra (Berberis aristata) (480 g), Yashtimadhu (Glycyrrhiza glabra) (480 g), Rasna (Pluchea lanceolata) (480 g), Vidari (Pueraria tuberosa) (480 g), Arjuna (Terminalia arjuna) (480 g), Musta (Cyperus rotundus) (480 g), Trivrit (Operculina turpethum) (480 g), Dhataki pushpa (Woodfordia fruticosa flower) (768 g (fermentation starter)), Madhu (Honey) (14.4 kg)

Therapeutic Indications: M, u, r, c, h, a,  , (, F, a, i, n, t, i, n, g,  , /,  , S, y, n, c, o, p, e, ), ,,  , A, p, a, s, m, a, r, a,  , (, E, p, i, l, e, p, s, y,  , /,  , C, o, n, v, u, l, s, i, v, e,  , d, i, s, o, r, d, e, r, s, ), ,,  , U, n, m, a, d, a,  , (, P, s, y, c, h, o, s, i, s,  , /,  , M, e, n, t, a, l,  , d, i, s, o, r, d, e, r, s, ), ,,  , K, a, r, s, h, y, a,  , (, E, m, a, c, i, a, t, i, o, n, ), ,,  , D, a, u, r, b, a, l, y, a,  , (, G, e, n, e, r, a, l,  , w, e, a, k, n, e, s, s, ), ,,  , S, m, r, i, t, i,  , K, s, h, a, y, a,  , (, M, e, m, o, r, y,  , l, o, s, s, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-brahmi-ghrita', 'Ayurvedic Formulary of India (AFI), Part I', 'Brahmi Ghrita', 'Brahmi Ghrita - AFI Part I (6:32)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Brahmi Ghrita

Sanskrit / Classical Name: ब्राह्मी घृत

Dosage Form: Ghrita (Medicated clarified butter)

Classical Reference / Authoritative Text: Ashtanga Hridaya, Uttarasthana, Adhyaya 6, Shloka 23-25; Charaka Samhita, Chikitsasthana 10:25; AFI Part I, 6:32

Key Botanical & Mineral Ingredients: Bacopa monnieri (Brahmi fresh juice / swarasa) (3.072 liters), Old Cow Ghee (Purana Go-Ghrita) (768 g), Acorus calamus (Vacha) (12 g), Saussurea lappa (Kushtha) (12 g), Convolvulus pluricaulis (Shankhapushpi) (12 g)

Therapeutic Indications: U, n, m, a, d, a,  , (, P, s, y, c, h, o, s, i, s, ), ,,  , A, p, a, s, m, a, r, a,  , (, E, p, i, l, e, p, s, y, ), ,,  , G, r, a, h, a, r, o, g, a, ,,  , M, e, d, h, a,  , V, a, r, d, h, a, k, a,  , (, N, o, o, t, r, o, p, i, c,  , /,  , C, o, g, n, i, t, i, v, e,  , e, n, h, a, n, c, e, m, e, n, t, ), ,,  , S, m, r, i, t, i,  , V, a, r, d, h, a, n, a,  , (, M, e, m, o, r, y,  , b, o, o, s, t, e, r, ), ,,  , B, u, d, d, h, i,  , V, a, r, d, h, a, n, a,  , (, I, n, t, e, l, l, e, c, t,  , e, n, h, a, n, c, e, r, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-sitopaladi-churna', 'Ayurvedic Formulary of India (AFI), Part I', 'Sitopaladi Churna', 'Sitopaladi Churna - AFI Part I (7:37)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Sitopaladi Churna

Sanskrit / Classical Name: सितोपलादि चूर्ण

Dosage Form: Churna (Herbal powder)

Classical Reference / Authoritative Text: Sharangadhara Samhita, Madhyama Khanda, Adhyaya 6, Shloka 134-137; Bhaishajya Ratnavali, Rajayakshmadhikara; AFI Part I, 7:37

Key Botanical & Mineral Ingredients: Sitopala (Sugar candy) (16 parts), Bambusa bambos (Vamshalochana / Bamboo silica) (8 parts), Piper longum (Pippali fruit) (4 parts), Elettaria cardamomum (Ela seeds) (2 parts), Cinnamomum zeylanicum (Twak / Cinnamon bark) (1 part)

Therapeutic Indications: K, a, s, a,  , (, C, o, u, g, h, ), ,,  , S, h, w, a, s, a,  , (, B, r, o, n, c, h, i, t, i, s,  , /,  , A, s, t, h, m, a, ), ,,  , R, a, j, a, y, a, k, s, h, m, a,  , (, T, u, b, e, r, c, u, l, o, s, i, s,  , /,  , W, a, s, t, i, n, g, ), ,,  , M, a, n, d, a, g, n, i,  , (, I, m, p, a, i, r, e, d,  , d, i, g, e, s, t, i, o, n, ), ,,  , S, u, p, t, a, j, i, h, v, a,  , (, L, o, s, s,  , o, f,  , s, e, n, s, a, t, i, o, n,  , o, n,  , t, o, n, g, u, e, ), ,,  , P, a, r, s, h, w, a, s, h, o, o, l, a,  , (, P, l, e, u, r, o, d, y, n, i, a,  , /,  , C, h, e, s, t,  , p, a, i, n, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-avipattikar-churna', 'Ayurvedic Formulary of India (AFI), Part I', 'Avipattikar Churna', 'Avipattikar Churna - AFI Part I (7:2)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Avipattikar Churna

Sanskrit / Classical Name: अविपत्तिकर चूर्ण

Dosage Form: Churna (Digestive powder)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Amlapitta Rogadhikara, Shloka 25-27; Sharangadhara Samhita, Madhyama Khanda 6:130; AFI Part I, 7:2

Key Botanical & Mineral Ingredients: Zingiber officinale (Shunthi) (1 part), Piper nigrum (Maricha) (1 part), Piper longum (Pippali) (1 part), Terminalia chebula (Haritaki) (1 part), Terminalia bellirica (Bibhitaki) (1 part), Phyllanthus emblica (Amalaki) (1 part), Cyperus rotundus (Musta) (1 part), Vida Lavana (Salt) (1 part), Embelia ribes (Vidanga) (1 part), Elettaria cardamomum (Ela) (1 part), Cinnamomum tamala (Tejapatra) (1 part), Syzygium aromaticum (Lavanga) (11 parts), Operculina turpethum (Trivrit) (44 parts), Sharkara (Sugar candy) (66 parts)

Therapeutic Indications: A, m, l, a, p, i, t, t, a,  , (, H, y, p, e, r, a, c, i, d, i, t, y,  , /,  , G, E, R, D, ), ,,  , V, i, b, a, n, d, h, a,  , (, C, o, n, s, t, i, p, a, t, i, o, n, ), ,,  , A, g, n, i, m, a, n, d, y, a,  , (, D, y, s, p, e, p, s, i, a, ), ,,  , A, r, s, h, a,  , (, P, i, l, e, s, ), ,,  , M, u, t, r, a, k, r, i, c, c, h, r, a,  , (, D, y, s, u, r, i, a, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-arogyavardhini-vati', 'Ayurvedic Formulary of India (AFI), Part I, First Schedule DCA 1940', 'Arogyavardhini Vati / Gutika', 'Arogyavardhini Vati - AFI Part I (20:4)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Arogyavardhini Vati / Gutika

Sanskrit / Classical Name: आरोग्यवर्धिनी वटी

Dosage Form: Vati / Rasaushadhi (Herbo-mineral pill)

Classical Reference / Authoritative Text: Rasaratna Samucchaya, Adhyaya 20, Shloka 87-93; Bhaishajya Ratnavali, Kushtharogadhikara; AFI Part I, 20:4

Key Botanical & Mineral Ingredients: Shuddha Parada (Purified Mercury) (1 part), Shuddha Gandhaka (Purified Sulphur) (1 part (triturated to Kajjali)), Lauha Bhasma (Calcined Iron) (1 part), Abhraka Bhasma (Calcined Mica) (1 part), Tamra Bhasma (Calcined Copper) (1 part), Triphala (Haritaki, Bibhitaki, Amalaki) (2 parts each (total 6)), Shilajit (Purified Asphaltum) (3 parts), Shuddha Guggulu (Commiphora mukul) (4 parts), Plumbago zeylanica (Chitraka root) (4 parts), Picrorhiza kurroa (Katuki rhizome) (22 parts), Azadirachta indica (Nimba patra swarasa - Neem juice) (Bhavana liquid for 2 days)

Therapeutic Indications: Y, a, k, r, i, t,  , R, o, g, a,  , (, H, e, p, a, t, i, c,  , d, i, s, o, r, d, e, r, s,  , /,  , F, a, t, t, y,  , l, i, v, e, r,  , /,  , H, e, p, a, t, i, t, i, s, ), ,,  , J, w, a, r, a,  , (, C, h, r, o, n, i, c,  , f, e, v, e, r, ), ,,  , K, u, s, h, t, h, a,  , (, S, k, i, n,  , d, i, s, o, r, d, e, r, s,  , /,  , E, c, z, e, m, a,  , /,  , P, s, o, r, i, a, s, i, s, ), ,,  , M, e, d, o, r, o, g, a,  , (, O, b, e, s, i, t, y,  , /,  , D, y, s, l, i, p, i, d, e, m, i, a, ), ,,  , D, e, e, p, a, n, a, ,,  , P, a, c, h, a, n, a, ,,  , M, a, l, a, s, h, o, d, h, a, k, a, .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-dashamularishta', 'Ayurvedic Formulary of India (AFI), Part I', 'Dashamularishta', 'Dashamularishta - AFI Part I (1:18)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Dashamularishta

Sanskrit / Classical Name: दशमूलारिष्ट

Dosage Form: Arishta (Fermented herbal elixir)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Sharangadhara Samhita; AFI Part I, 1:18

Key Botanical & Mineral Ingredients: Dashamula (10 roots: Bilva, Agnimantha, Shyonaka, Patala, Gambhari, Shalaparni, Prishniparni, Brihati, Kantakari, Gokshura) (Total 4.8 kg), Chitraka, Pushkaramula, Lodhra, Guduchi, Dhatri, Duralabha, Khadira, Bijaka, Triphala, Kushta, Manjishta, Devadaru, Vidanga, Yashti (Each 48 g), Draksha (Raisins) (3.2 kg), Dhataki flowers (Woodfordia fruticosa) (768 g), Jaggery (Guda) (19.2 kg)

Therapeutic Indications: S, u, t, i, k, a,  , R, o, g, a,  , (, P, o, s, t, -, p, a, r, t, u, m,  , r, e, c, o, v, e, r, y,  , a, n, d,  , d, i, s, o, r, d, e, r, s, ), ,,  , V, a, t, a, v, y, a, d, h, i,  , (, D, e, g, e, n, e, r, a, t, i, v, e,  , n, e, u, r, o, l, o, g, i, c, a, l,  , c, o, n, d, i, t, i, o, n, s, ), ,,  , G, r, a, h, a, n, i,  , (, I, B, S, ), ,,  , A, r, u, c, h, i,  , (, A, n, o, r, e, x, i, a, ), ,,  , S, h, w, a, s, a, ,,  , K, a, s, a, ,,  , D, a, u, r, b, a, l, y, a, .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-kanchnar-guggulu', 'Ayurvedic Formulary of India (AFI), Part I', 'Kanchnar Guggulu', 'Kanchnar Guggulu - AFI Part I (5:1)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Kanchnar Guggulu

Sanskrit / Classical Name: काञ्चनार गुग्गुलु

Dosage Form: Vati (Guggulu tablet)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Galagandadi Rogadhikara, Shloka 31-35; Sharangadhara Samhita 7:95; AFI Part I, 5:1

Key Botanical & Mineral Ingredients: Bauhinia variegata (Kanchnar bark) (10 parts), Triphala (Haritaki, Bibhitaki, Amalaki) (2 parts each (total 6)), Trikatu (Shunthi, Maricha, Pippali) (1 part each (total 3)), Crataeva nurvala (Varuna bark) (1 part), Elettaria cardamomum (Ela) (0.5 part), Cinnamomum zeylanicum (Twak) (0.5 part), Cinnamomum tamala (Tejapatra) (0.5 part), Commiphora mukul (Shuddha Guggulu) (21.5 parts)

Therapeutic Indications: G, a, l, a, g, a, n, d, a,  , (, G, o, i, t, r, e,  , /,  , T, h, y, r, o, i, d,  , s, w, e, l, l, i, n, g, s, ), ,,  , G, a, n, d, a, m, a, l, a,  , (, C, e, r, v, i, c, a, l,  , l, y, m, p, h, a, d, e, n, i, t, i, s,  , /,  , S, c, r, o, f, u, l, a, ), ,,  , G, r, a, n, t, h, i,  , (, B, e, n, i, g, n,  , t, u, m, o, r, s,  , /,  , C, y, s, t, s,  , /,  , F, i, b, r, o, i, d, s,  , /,  , P, C, O, S, ), ,,  , A, r, b, u, d, a, ,,  , A, p, a, c, h, i, .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-punarnavadi-kwatha', 'Ayurvedic Formulary of India (AFI), Part I', 'Punarnavadi Kwatha', 'Punarnavadi Kwatha - AFI Part I (4:21)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Punarnavadi Kwatha

Sanskrit / Classical Name: पुनर्नवादि क्वाथ

Dosage Form: Kwatha / Kashaya (Herbal decoction)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Shotharogadhikara, Shloka 48; Sahasrayogam; AFI Part I, 4:21

Key Botanical & Mineral Ingredients: Boerhavia diffusa (Punarnava root) (1 part), Azadirachta indica (Nimba bark) (1 part), Trichosanthes dioica (Patola leaf) (1 part), Zingiber officinale (Shunthi) (1 part), Picrorhiza kurroa (Katuki) (1 part), Tinospora cordifolia (Guduchi) (1 part), Cedrus deodara (Devadaru) (1 part), Terminalia chebula (Haritaki) (1 part)

Therapeutic Indications: S, a, r, v, a, n, g, a,  , S, h, o, t, h, a,  , (, G, e, n, e, r, a, l, i, z, e, d,  , e, d, e, m, a,  , /,  , A, n, a, s, a, r, c, a, ), ,,  , U, d, a, r, a,  , R, o, g, a,  , (, A, s, c, i, t, e, s, ), ,,  , K, a, m, a, l, a,  , (, J, a, u, n, d, i, c, e, ), ,,  , K, a, s, a, ,,  , S, h, w, a, s, a, ,,  , S, h, o, o, l, a, .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-kumkumadi-taila', 'Ayurvedic Formulary of India (AFI), Part I', 'Kumkumadi Taila', 'Kumkumadi Taila - AFI Part I (8:10)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Kumkumadi Taila

Sanskrit / Classical Name: कुंकुमादि तैल

Dosage Form: Taila (Medicated cosmetic and therapeutic oil)

Classical Reference / Authoritative Text: Bhaishajya Ratnavali, Kshudrarogadhikara, Shloka 63-69; Yogaratnakara; AFI Part I, 8:10

Key Botanical & Mineral Ingredients: Crocus sativus (Kumkuma / Saffron stigma) (12 g), Pterocarpus santalinus (Rakta Chandana) (12 g), Rubia cordifolia (Manjishta) (12 g), Glycyrrhiza glabra (Yashtimadhu) (12 g), Nelumbo nucifera (Kamala flower) (12 g), Ficus benghalensis (Nyagrodha aerial roots) (12 g), Prunus cerasoides (Padmaka) (12 g), Sesamum indicum oil (Tila Taila) (768 ml), Goat''s Milk (Aja Dugdha) (1.536 liters)

Therapeutic Indications: M, u, k, h, a, d, u, s, h, i, k, a,  , (, A, c, n, e,  , v, u, l, g, a, r, i, s, ), ,,  , V, y, a, n, g, a,  , (, M, e, l, a, s, m, a,  , /,  , F, a, c, i, a, l,  , p, i, g, m, e, n, t, a, t, i, o, n, ), ,,  , T, i, l, a, k, a, l, a, k, a,  , (, F, r, e, c, k, l, e, s, ), ,,  , V, a, r, n, y, a, k, a, r, a,  , (, C, o, m, p, l, e, x, i, o, n,  , p, r, o, m, o, t, e, r, ), ,,  , V, r, a, n, a, r, o, p, a, k, a,  , (, W, o, u, n, d,  , h, e, a, l, i, n, g, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-anu-taila', 'Ayurvedic Formulary of India (AFI), Part I', 'Anu Taila', 'Anu Taila - AFI Part I (8:1)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Anu Taila

Sanskrit / Classical Name: अणु तैल

Dosage Form: Taila / Nasya (Nasal drop medicated oil)

Classical Reference / Authoritative Text: Charaka Samhita, Sutrasthana, Adhyaya 5, Shloka 56-62; Ashtanga Hridaya, Sutrasthana 20; AFI Part I, 8:1

Key Botanical & Mineral Ingredients: Holostemma ada-kodien (Jivanti) (1 part), Coleus vettiveroides (Hrivera) (1 part), Cedrus deodara (Devadaru) (1 part), Cyperus rotundus (Musta) (1 part), Cinnamomum zeylanicum (Twak) (1 part), Vetiveria zizanioides (Ushira) (1 part), Hemidesmus indicus (Sariva) (1 part), Santalum album (Chandana) (1 part), Berberis aristata (Daruharidra) (1 part), Glycyrrhiza glabra (Yashtimadhu) (1 part), Sesame oil (Tila Taila) (Vehicle), Goat''s Milk (Aja Kshira) (Vehicle)

Therapeutic Indications: S, h, i, r, o, g, a, t, a,  , R, o, g, a,  , (, D, i, s, o, r, d, e, r, s,  , o, f,  , h, e, a, d,  , a, n, d,  , n, e, c, k, ), ,,  , S, u, r, y, a, v, a, r, t, a,  , (, S, i, n, u, s, i, t, i, s,  , /,  , M, i, g, r, a, i, n, e, ), ,,  , M, a, n, y, a, s, t, a, m, b, h, a,  , (, C, e, r, v, i, c, a, l,  , s, p, o, n, d, y, l, o, s, i, s, ), ,,  , K, h, a, l, i, t, y, a,  , (, A, l, o, p, e, c, i, a, ), ,,  , P, a, l, i, t, y, a,  , (, P, r, e, m, a, t, u, r, e,  , g, r, a, y, i, n, g,  , o, f,  , h, a, i, r, ), ,,  , I, n, d, r, i, y, a, p, r, a, b, o, d, h, a,  , (, S, e, n, s, o, r, y,  , o, r, g, a, n,  , r, e, j, u, v, e, n, a, t, i, o, n,  , v, i, a,  , N, a, s, y, a, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-afi-trikatu-churna', 'Ayurvedic Formulary of India (AFI), Part I', 'Trikatu Churna', 'Trikatu Churna - AFI Part I (7:13)', 'india', 'pharmacopoeia', 'https://main.ayush.gov.in', 'Formulation: Trikatu Churna

Sanskrit / Classical Name: त्रिकटु चूर्ण

Dosage Form: Churna (Bio-enhancer powder)

Classical Reference / Authoritative Text: Sharangadhara Samhita, Madhyama Khanda 6:12; Charaka Samhita; AFI Part I, 7:13

Key Botanical & Mineral Ingredients: Zingiber officinale (Shunthi / Dried ginger) (1 part (33.3%)), Piper nigrum (Maricha / Black pepper) (1 part (33.3%)), Piper longum (Pippali / Long pepper) (1 part (33.3%))

Therapeutic Indications: A, g, n, i, m, a, n, d, y, a,  , (, L, o, s, s,  , o, f,  , a, p, p, e, t, i, t, e, ), ,,  , G, a, l, a, s, h, u, n, d, i, k, a,  , (, T, h, r, o, a, t,  , d, i, s, o, r, d, e, r, s, ), ,,  , P, i, n, a, s, a,  , (, R, h, i, n, i, t, i, s, ), ,,  , S, h, w, a, s, a, ,,  , K, a, s, a, ,,  , K, u, s, h, t, a, ,,  , D, e, e, p, a, n, a, ,,  , P, a, c, h, a, n, a, ,,  , B, i, o, a, v, a, i, l, a, b, i, l, i, t, y,  , e, n, h, a, n, c, e, r,  , (, Y, o, g, a, v, a, h, i, ), .');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-dca-sec3-a', 'The Drugs and Cosmetics Act, 1940 (Act No. 23 of 1940)', 'Section 3(a)', 'Section 3(a) - Definition of Ayurvedic, Siddha or Unani Drug', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2366', '''Ayurvedic, Siddha or Unani drug'' includes all medicines intended for internal or external use for or in the diagnosis, treatment, mitigation or prevention of disease or disorder in human beings or animals, and manufactured exclusively in accordance with the formulae described in the authoritative books of Ayurvedic, Siddha and Unani Tibb systems of medicine, specified in the First Schedule.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-dca-sec3-h', 'The Drugs and Cosmetics Act, 1940', 'Section 3(h)', 'Section 3(h) - Patent or Proprietary Medicine (Ayurvedic/ASU)', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2366', 'In relation to Ayurvedic, Siddha or Unani Tibb systems of medicine, ''patent or proprietary medicine'' means a drug which is a formulation containing only ingredients mentioned in the formulae described in the authoritative books of Ayurveda, Siddha or Unani Tibb systems of medicine specified in the First Schedule, but does not include a medicine which is administered by parenteral route and also a formulation which is not specified in the First Schedule.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-dca-first-schedule', 'The Drugs and Cosmetics Act, 1940', 'The First Schedule', 'The First Schedule - Authoritative Books of ASU Systems', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2366', 'Specifies the 56 authoritative texts for Ayurveda including: Charaka Samhita, Sushruta Samhita, Ashtanga Hridaya, Ashtanga Samgraha, Sharangadhara Samhita, Bhaishajya Ratnavali, Chakradatta, Rasendra Sara Sangraha, Rasa Ratna Samucchaya, Sahasrayogam, Yogaratnakara, Ayurvedic Formulary of India (AFI Parts I, II, III), and Ayurvedic Pharmacopoeia of India (API). Any classical drug claiming Section 3(a) status MUST be prepared strictly according to recipes in these 56 texts.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-dca-sec33ee', 'The Drugs and Cosmetics Act, 1940', 'Section 33EE', 'Section 33EE - Misbranded Ayurvedic Drugs', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2366', 'An Ayurvedic drug shall be deemed to be misbranded if: (a) it is so coloured, coated, powdered or polished that damage is concealed, or if it is made to appear of better or greater therapeutic value than it really is; or (b) it is not labelled in the prescribed manner; or (c) its label or container or anything accompanying the drug bears any statement, design or device which makes any false claim for the drug or which is false or misleading in any particular.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-dca-sec33eeb', 'The Drugs and Cosmetics Act, 1940', 'Section 33EEB', 'Section 33EEB - Spurious Ayurvedic Drugs', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/2366', 'An Ayurvedic drug shall be deemed to be spurious: (a) if it is manufactured under a name which belongs to another drug; or (b) if it is an imitation of, or a substitute for, another drug; or (c) if it purports to be the product of a manufacturer of whom it is not truly a product; or (d) if it has been substituted wholly or in part by another drug or substance.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-dca-schedule-t', 'The Drugs and Cosmetics Rules, 1945', 'Schedule T (D&C Rules 1945)', 'Schedule T - Good Manufacturing Practices (GMP) for Ayurvedic Drugs', 'india', 'rule', 'https://cdsco.gov.in', 'Schedule T mandates factory premises, hygiene, raw material storage, machinery equipment, quality control section, raw material identification (botanical authentication, TLC fingerprinting, pesticide residue tests, heavy metals testing - Lead, Cadmium, Arsenic, Mercury), batch manufacturing records (BMR), and stability testing for all licensed ASU manufacturers in India. Non-compliance results in cancellation of manufacturing license under Rule 158.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-dca-rule-158-b', 'The Drugs and Cosmetics Rules, 1945', 'Rule 158-B (D&C Rules 1945)', 'Rule 158-B - Guidelines for Issue of License with respect to ASU Drugs', 'india', 'rule', 'https://cdsco.gov.in', 'Provides evidentiary requirements for licensing ASU drugs in India: Category 1 (Classical ASU Drugs): Proof of reference in First Schedule texts, no safety/efficacy trials needed. Category 2 (Patent or Proprietary): Category 2(A) (Ingredients from authoritative texts with same indications): Published literature on safety and evidence of efficacy. Category 2(B) (New combination with new indication): Acute/sub-acute toxicity studies, published clinical trials or pilot clinical trials. Category 2(C) (Extracts of classical plants / Purified fractions): Complete phase I/II/III toxicological and clinical trial data similar to new chemical entities.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-fssai-ayush-reg3', 'Food Safety and Standards (Ayush Aahar) Regulations, 2022', 'Regulation 3', 'Regulation 3 - Definition and Scope of Ayush Aahar', 'india', 'regulation', 'https://fssai.gov.in', '''Ayush Aahar'' means food manufactured or prepared in accordance with the recipes or books/texts specified in the First Schedule of the Drugs and Cosmetics Act, 1940, and other authoritative books of Ayurveda, Siddha and Unani specified under the regulations, including health foods, dietary supplements and functional foods prepared from botanical ingredients. Ayush Aahar does not include drugs defined under Section 3(b) or Section 3(a) of the D&C Act, nor synthetic vitamins/minerals/amino acids.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-fssai-ayush-reg5', 'Food Safety and Standards (Ayush Aahar) Regulations, 2022', 'Regulation 5', 'Regulation 5 - Prohibition of Therapeutic and Medicinal Claims', 'india', 'regulation', 'https://fssai.gov.in', 'Ayush Aahar products shall NOT claim to prevent, treat, cure, mitigate, or diagnose any specific disease or pathological condition in human beings. Permissible claims are strictly restricted to health promotion, nutritional support, physiological balance (Dosha balance), immunity enhancement, and general wellness. Any product carrying therapeutic or curative claims shall be deemed an Ayurvedic Drug and must obtain a license from State AYUSH Licensing Authorities under D&C Act 1940 instead of FSSAI.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-gi-sec2-1-e', 'The Geographical Indications of Goods (Registration and Protection) Act, 1999 (Act No. 48 of 1999)', 'Section 2(1)(e)', 'Section 2(1)(e) - Definition of Geographical Indication', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1981', '''geographical indication'', in relation to goods, means an indication which identifies such goods as agricultural goods, natural goods or manufactured goods as originating, or manufactured in the territory of a country, or a region or locality in that territory, where a given quality, reputation or other characteristic of such goods is essentially attributable to its geographical origin and in case where such goods are manufactured goods one of the activities of either the production or of processing or preparation of the goods concerned takes place in such territory, region or locality, as the case may be.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-gi-sec9', 'The Geographical Indications of Goods Act, 1999', 'Section 9', 'Section 9 - Prohibition of Registration of Certain Geographical Indications', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1981', 'A geographical indication: (a) the use of which would be likely to deceive or cause confusion; or (b) the use of which would be contrary to any law for the time being in force; or (c) which comprises or contains scandalous or obscene matter; or (d) which comprises or contains any matter likely to hurt the religious susceptibilities of any class or section of the citizens of India; or (e) which would otherwise be disentitled to protection in a court; or (f) which are determined to be generic names or indications of goods and have, therefore, ceased to be protected in their country of origin, or which have fallen into disuse in that country; or (g) which, although literally true as to the country, territory or locality in which the goods originate, falsely represent to the public that the goods originate in another territory, shall not be registered.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-gi-sec21', 'The Geographical Indications of Goods Act, 1999', 'Section 21', 'Section 21 - Rights Conferred by Registration of Geographical Indication', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1981', 'The registration of a geographical indication shall give to the registered proprietor and the authorized user the right to obtain relief in respect of infringement of the geographical indication in the manner provided by this Act; and to the authorized user thereof the exclusive right to the use of the geographical indication in relation to the goods in respect of which the geographical indication is registered.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec2-1-j', 'The Patents Act, 1970 (Act No. 39 of 1970)', 'Section 2(1)(j)', 'Section 2(1)(j) - Definition of Invention', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', '''invention'' means a new product or process involving an inventive step and capable of industrial application. For an invention to be patentable, it must satisfy three cumulative criteria: novelty (not anticipated in prior art anywhere in the world), inventive step (a feature of an invention that involves technical advance as compared to existing knowledge or having economic significance or both and that makes the invention not obvious to a person skilled in the art), and utility / industrial applicability.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-a', 'The Patents Act, 1970', 'Section 3(a)', 'Section 3(a) - Inventions contrary to natural laws or frivolous', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (a) an invention which is frivolous or which claims anything obviously contrary to well established natural laws.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-b', 'The Patents Act, 1970', 'Section 3(b)', 'Section 3(b) - Contrary to public order or morality or injurious to health', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (b) an invention the primary or intended use or commercial exploitation of which could be contrary to public order or morality or which causes serious prejudice to human, animal or plant life or health or to the environment.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-c', 'The Patents Act, 1970', 'Section 3(c)', 'Section 3(c) - Mere discovery of scientific principle or living thing', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (c) the mere discovery of a scientific principle or the formulation of an abstract theory or discovery of any living thing or non-living substance occurring in nature. Pure natural plant extracts, unisolated native phytochemicals, or naturally occurring botanical species cannot be claimed as patentable subject matter.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-d', 'The Patents Act, 1970', 'Section 3(d)', 'Section 3(d) - Mere discovery of new form of known substance without enhanced efficacy', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (d) the mere discovery of a new form of a known substance which does not result in the enhancement of the known efficacy of that substance or the mere discovery of any new property or new use for a known substance or of the mere use of a known process, machine or apparatus unless such known process results in a new product or employs at least one new reactant. Explanation.—For the purposes of this clause, salts, esters, ethers, polymorphs, metabolites, pure form, particle size, isomers, mixtures of isomers, complexes, combinations and other derivatives of known substance shall be considered to be the same substance, unless they differ significantly in properties with regard to efficacy.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-e', 'The Patents Act, 1970', 'Section 3(e)', 'Section 3(e) - Mere admixture resulting only in aggregation of properties', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (e) a substance obtained by a mere admixture resulting only in aggregation of the properties of the components thereof or a process for producing such substance. In AYUSH formulations, simply mixing two or more known herbs (e.g. Ashwagandha + Shatavari) without demonstrating unexpected synergism (synergistic ratio substantiated by experimental comparative bioassay data) falls squarely under Section 3(e) and is rejected.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-h', 'The Patents Act, 1970', 'Section 3(h)', 'Section 3(h) - Method of agriculture or horticulture', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (h) a method of agriculture or horticulture. Cultivation techniques for medicinal plants, wild harvesting protocols, or nursery propagation methods cannot be patented.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-i', 'The Patents Act, 1970', 'Section 3(i)', 'Section 3(i) - Method of treatment of human beings or animals', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (i) any process for the medicinal, surgical, curative, prophylactic, diagnostic, therapeutic or other treatment of human beings or any similar treatment of animals to render them free of disease or to increase their economic value or that of their products. Methods of treating diseases with herbal extracts or dosage regimens cannot be patented in India; only novel, synergistic compositions or novel extraction processes can be claimed.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-j', 'The Patents Act, 1970', 'Section 3(j)', 'Section 3(j) - Plants and animals in whole or any part thereof', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (j) plants and animals in whole or any part thereof other than micro-organisms, but including seeds, varieties and species and essentially biological processes for production or propagation of plants and animals. Plant varieties are protectable under the Protection of Plant Varieties and Farmers'' Rights Act, 2001 (PPVFR Act), not under the Patents Act.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec3-p', 'The Patents Act, 1970', 'Section 3(p)', 'Section 3(p) - Traditional Knowledge or aggregation/duplication thereof', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'The following are not inventions within the meaning of this Act: (p) an invention which in effect, is traditional knowledge or which is an aggregation or duplication of known properties of traditionally known component or components. Added by the Patents (Amendment) Act 2002 to codify protection of Indian traditional medicine (Ayurveda, Unani, Siddha, Sowa-Rigpa) against bio-piracy. If an ingredient or formulation is documented in the Ayurvedic Formulary of India (AFI), Ayurvedic Pharmacopoeia of India (API), Charaka Samhita, Sushruta Samhita, Ashtanga Hridaya, Sharangadhara Samhita, Bhaishajya Ratnavali, or the Traditional Knowledge Digital Library (TKDL), it is unpatentable as an invention per se under Section 3(p).');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec10-4', 'The Patents Act, 1970', 'Section 10(4)', 'Section 10(4) - Mandatory Disclosure of Biological Material Source & NBA Approval', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'Every complete specification shall: (d) disclose the source and geographical origin of the biological material in the specification, when used in an invention. If the biological material is obtained from India, the applicant must disclose the exact location and obtain prior permission from the National Biodiversity Authority (NBA) under Section 6 of the Biological Diversity Act, 2002 before the grant of the patent. Failure to disclose or wrongful disclosure of source/origin is an explicit ground for pre-grant opposition under Section 25(1)(j), post-grant opposition under Section 25(2)(j), and revocation of the patent under Section 64(1)(p).');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec25', 'The Patents Act, 1970', 'Section 25', 'Section 25 - Opposition to the Grant of Patent (Pre-grant and Post-grant)', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'Under Section 25(1), any person may file a pre-grant opposition in writing against the grant of patent on grounds including: (d) that the invention was publicly known or publicly used in India; (f) that the subject of any claim is not an invention within the meaning of this Act, or is not patentable under Section 3; (k) that the complete specification does not disclose or wrongly mentions the source or geographical origin of biological material used for the invention; (k) that the invention so far as claimed in any claim of the complete specification is anticipated having regard to the knowledge, oral or otherwise, available within any local or indigenous community in India or elsewhere. This enables TKDL and third parties to prevent illegitimate patents.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('in-patent-sec64-1-p', 'The Patents Act, 1970', 'Section 64(1)(p)', 'Section 64(1)(p) - Revocation for Non-disclosure or Anticipation by Traditional Knowledge', 'india', 'statute', 'https://www.indiacode.nic.in/handle/123456789/1392', 'A patent may be revoked on petition of any person interested or the Central Government on the grounds: (p) that the complete specification does not disclose or wrongly mentions the source or geographical origin of biological material used for the invention; (q) that the invention so far as claimed in any claim of the complete specification was anticipated having regard to the knowledge, oral or otherwise, available within any local or indigenous community in India or elsewhere.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-cbd-art8-j', 'Convention on Biological Diversity (CBD), 1992', 'Article 8(j)', 'Article 8(j) - Traditional Knowledge, Innovations and Practices', 'international', 'treaty', 'https://www.cbd.int/doc/legal/cbd-en.pdf', 'Each Contracting Party shall, as far as possible and as appropriate: Subject to its national legislation, respect, preserve and maintain knowledge, innovations and practices of indigenous and local communities embodying traditional lifestyles relevant for the conservation and sustainable use of biological diversity and promote their wider application with the approval and involvement of the holders of such knowledge, innovations and practices and encourage the equitable sharing of the benefits arising from the utilization of such knowledge, innovations and practices.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-cbd-art15', 'Convention on Biological Diversity (CBD), 1992', 'Article 15', 'Article 15 - Access to Genetic Resources and National Sovereignty', 'international', 'treaty', 'https://www.cbd.int/doc/legal/cbd-en.pdf', '1. Recognizing the sovereign rights of States over their natural resources, the authority to determine access to genetic resources rests with the national governments and is subject to national legislation. 2. Each Contracting Party shall endeavour to create conditions to facilitate access to genetic resources for environmentally sound uses by other Contracting Parties and not to impose restrictions that run counter to the objectives of this Convention. 3. For the purpose of this Convention, the genetic resources being provided by a Contracting Party are only those that are provided by Contracting Parties that are countries of origin of such resources or by the Parties that have acquired the genetic resources in accordance with this Convention. 4. Access, where granted, shall be on mutually agreed terms and subject to the provisions of this Article. 5. Access to genetic resources shall be subject to prior informed consent of the Contracting Party providing such resources, unless otherwise determined by that Party.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-nagoya-art5', 'Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization to the Convention on Biological Diversity (2010)', 'Article 5', 'Article 5 - Fair and Equitable Benefit-Sharing', 'international', 'treaty', 'https://www.cbd.int/abs/text/', '1. In accordance with Article 15, paragraphs 3 and 7 of the Convention, benefits arising from the utilization of genetic resources as well as subsequent applications and commercialization shall be shared in a fair and equitable way with the Party providing such resources that is the country of origin of such resources or a Party that has acquired the genetic resources in accordance with the Convention. Such sharing shall be upon mutually agreed terms. 2. Each Party shall take legislative, administrative or policy measures, as appropriate, with the aim of ensuring that benefits arising from the utilization of genetic resources that are held by indigenous and local communities, in accordance with domestic legislation regarding the established rights of these indigenous and local communities over these genetic resources, are shared in a fair and equitable way with the communities concerned, based on mutually agreed terms.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-nagoya-art6', 'Nagoya Protocol, 2010', 'Article 6', 'Article 6 - Prior Informed Consent (PIC) for Access to Genetic Resources', 'international', 'treaty', 'https://www.cbd.int/abs/text/', '1. In the exercise of sovereign rights over natural resources, and subject to domestic access and benefit-sharing legislation or regulatory requirements, access to genetic resources for their utilization shall be subject to the prior informed consent of the Party providing such resources that is the country of origin of such resources or a Party that has acquired the genetic resources in accordance with the Convention, unless otherwise determined by that Party. 2. In accordance with domestic law, each Party shall take measures, as appropriate, with the aim of ensuring that the prior informed consent or approval and involvement of indigenous and local communities is obtained for access to genetic resources where they have the established right to grant access to such resources.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-nagoya-art7', 'Nagoya Protocol, 2010', 'Article 7', 'Article 7 - Access to Traditional Knowledge Associated with Genetic Resources', 'international', 'treaty', 'https://www.cbd.int/abs/text/', 'In accordance with domestic law, each Party shall take measures, as appropriate, with the aim of ensuring that traditional knowledge associated with genetic resources that is held by indigenous and local communities is accessed with the prior and informed consent or approval and involvement of these indigenous and local communities, and that mutually agreed terms have been established. This international obligation prevents foreign pharmaceutical and biotech corporations from accessing traditional indigenous remedies without explicit consent and fair financial/technological return.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-nagoya-art15-16', 'Nagoya Protocol, 2010', 'Articles 15 & 16', 'Articles 15 & 16 - Compliance with Domestic Legislation on ABS and TK', 'international', 'treaty', 'https://www.cbd.int/abs/text/', 'Each Party shall take appropriate, effective and proportionate legislative, administrative or policy measures to provide that genetic resources and traditional knowledge associated with genetic resources utilized within its jurisdiction have been accessed in accordance with prior informed consent and that mutually agreed terms have been established, as required by the domestic access and benefit-sharing legislation of the other Party. Parties shall cooperate in cases of alleged violation.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-pct-art15-33', 'Patent Cooperation Treaty (PCT), 1970 (as modified)', 'Articles 15 & 33', 'Articles 15 & 33 - International Search and International Preliminary Examination', 'international', 'treaty', 'https://www.wipo.int/pct/en/texts/', 'Article 15: Each international application shall be the subject of international search. The objective of the international search is to discover relevant prior art. The prior art shall consist of everything which has been made available to the public anywhere in the world by means of written disclosure (including patent documents, published scientific literature, and accessible traditional knowledge databases like TKDL). Article 33: The objective of international preliminary examination is to formulate a preliminary and non-binding opinion on whether the claimed invention appears to be novel, to involve an inventive step (to be non-obvious), and to be industrially applicable.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-trips-art27-1', 'Agreement on Trade-Related Aspects of Intellectual Property Rights (TRIPS), 1994', 'Article 27.1', 'Article 27.1 - Patentable Subject Matter', 'international', 'treaty', 'https://www.wto.org/english/docs_e/legal_e/27-trips_04c_e.htm#5', 'Subject to the provisions of paragraphs 2 and 3, patents shall be available for any inventions, whether products or processes, in all fields of technology, provided that they are new, involve an inventive step and are capable of industrial application. Subject to paragraph 4 of Article 65, paragraph 8 of Article 70 and paragraph 3 of this Article, patents shall be available and patent rights enjoyable without discrimination as to the place of invention, the field of technology and whether products are imported or locally produced.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-trips-art27-2', 'TRIPS Agreement, 1994', 'Article 27.2', 'Article 27.2 - Exclusions to Protect Ordre Public or Morality', 'international', 'treaty', 'https://www.wto.org/english/docs_e/legal_e/27-trips_04c_e.htm#5', 'Members may exclude from patentability inventions, the prevention within their territory of the commercial exploitation of which is necessary to protect ordre public or morality, including to protect human, animal or plant life or health or to avoid serious prejudice to the environment, provided that such exclusion is not made merely because the exploitation is prohibited by their law.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-trips-art27-3-b', 'TRIPS Agreement, 1994', 'Article 27.3(b)', 'Article 27.3(b) - Exclusions for Plants, Animals and Biological Processes', 'international', 'treaty', 'https://www.wto.org/english/docs_e/legal_e/27-trips_04c_e.htm#5', 'Members may also exclude from patentability: (a) diagnostic, therapeutic and surgical methods for the treatment of humans or animals; (b) plants and animals other than micro-organisms, and essentially biological processes for the production of plants or animals other than non-biological and microbiological processes. However, Members shall provide for the protection of plant varieties either by patents or by an effective sui generis system or by any combination thereof.');
INSERT INTO corpus_chunks (chunk_id, statute, section_or_article, title, jurisdiction, doc_type, url, text_content) VALUES ('intl-trips-art29', 'TRIPS Agreement, 1994', 'Article 29', 'Article 29 - Conditions on Patent Applicants (Sufficiency of Disclosure)', 'international', 'treaty', 'https://www.wto.org/english/docs_e/legal_e/27-trips_04c_e.htm#5', '1. Members shall require that an applicant for a patent shall disclose the invention in a manner sufficiently clear and complete for the invention to be carried out by a person skilled in the art and may require the applicant to indicate the best mode for carrying out the invention known to the inventor at the filing date or, where priority is claimed, at the priority date of the application. 2. Members may require an applicant for a patent to provide information concerning the applicant''s corresponding foreign applications and grants.');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec3-p', 'CROSS_REFERENCES', 'Section 3(p) inventions are grounds for pre-grant opposition under Section 25(1)(f)', 'in-patent-sec25');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec3-p', 'CROSS_REFERENCES', 'Section 3(p) violations are grounds for revocation under Section 64(1)(p)', 'in-patent-sec64-1-p');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec3-d', 'CROSS_REFERENCES', 'Known substance (3d) and mere admixture (3e) are co-assessed for Ayurvedic formulations', 'in-patent-sec3-e');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec3-e', 'CROSS_REFERENCES', 'Mere admixture (3e) and traditional knowledge (3p) are co-bars for classical herb combinations', 'in-patent-sec3-p');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec10-4', 'CROSS_REFERENCES', 'Non-disclosure of bio-material source (10(4)) is ground for opposition under 25(1)(j)', 'in-patent-sec25');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec10-4', 'CROSS_REFERENCES', 'Non-disclosure of bio-material source is ground for revocation under 64(1)(p)', 'in-patent-sec64-1-p');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec2-1-j', 'CROSS_REFERENCES', 'Definition of invention (2(1)(j)) is qualified by non-patentable exclusions under Section 3', 'in-patent-sec3-a');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec10-4', 'CROSS_REFERENCES', 'Patent applications on Indian bio-resources require NBA approval under BDA Section 6', 'in-bda-sec6');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec6', 'CROSS_REFERENCES', 'NBA IPR approval requirement links to patent disclosure obligations under Patents Act 10(4)', 'in-patent-sec10-4');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec3', 'CROSS_REFERENCES', 'Contravention of Section 3 (foreign access) triggers penalties under Section 55', 'in-bda-sec55');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec6', 'CROSS_REFERENCES', 'Contravention of Section 6 (IPR without NBA) triggers penalties under Section 55', 'in-bda-sec55');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec6', 'CROSS_REFERENCES', 'NBA approval under Section 6 is linked to benefit sharing under Section 21', 'in-bda-sec21');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-dca-sec3-a', 'CROSS_REFERENCES', 'Classical ASU drug definition (3(a)) depends on authoritative texts listed in First Schedule', 'in-dca-first-schedule');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-dca-sec3-h', 'CROSS_REFERENCES', 'P&P medicine definition (3(h)) references ingredients from First Schedule texts', 'in-dca-first-schedule');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-dca-sec3-h', 'CROSS_REFERENCES', 'P&P medicines require licensing under Rule 158-B categories', 'in-dca-rule-158-b');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-dca-sec3-a', 'CROSS_REFERENCES', 'Classical drugs are Category 1 under Rule 158-B licensing', 'in-dca-rule-158-b');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-dca-sec3-a', 'CROSS_REFERENCES', 'Classical ASU drugs documented in First Schedule texts are barred from patenting under 3(p)', 'in-patent-sec3-p');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-dca-rule-158-b', 'CROSS_REFERENCES', 'Rule 158-B Category 2(C) extracts must overcome Section 3(d) efficacy enhancement bar', 'in-patent-sec3-d');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec3', 'IMPLEMENTS', 'BDA Section 3 implements Nagoya Protocol Article 6 PIC requirements domestically', 'intl-nagoya-art6');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec6', 'IMPLEMENTS', 'BDA Section 6 implements Nagoya Protocol Article 5 benefit sharing for IPR', 'intl-nagoya-art5');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec21', 'IMPLEMENTS', 'BDA Section 21 implements Nagoya Article 5 equitable benefit sharing', 'intl-nagoya-art5');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec3-p', 'IMPLEMENTS', 'Section 3(p) TK protection aligns with Nagoya Article 7 on TK access safeguards', 'intl-nagoya-art7');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('intl-nagoya-art5', 'CROSS_REFERENCES', 'Benefit sharing (Art 5) requires prior informed consent (Art 6)', 'intl-nagoya-art6');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('intl-nagoya-art6', 'CROSS_REFERENCES', 'PIC for genetic resources (Art 6) extends to traditional knowledge (Art 7)', 'intl-nagoya-art7');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('intl-nagoya-art7', 'CROSS_REFERENCES', 'TK access safeguards (Art 7) enforced by compliance mechanisms (Arts 15-16)', 'intl-nagoya-art15-16');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec3-p', 'AMENDS', 'Patents (Amendment) Act 2002 added Section 3(p) qualifying the definition of invention', 'in-patent-sec2-1-j');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-patent-sec3-d', 'AMENDS', 'Patents (Amendment) Act 2005 refined Section 3(d) enhanced efficacy requirement', 'in-patent-sec2-1-j');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec2-c', 'AMENDS', 'BDA Amendment 2023 exempted registered AYUSH practitioners from SBB intimation', 'in-bda-sec7');
INSERT INTO graph_edges (source_chunk_id, edge_type, label, target_chunk_id) VALUES ('in-bda-sec55', 'AMENDS', 'BDA Amendment 2023 changed criminal penalties to civil penalties with fines up to Rs 50 lakhs', 'in-bda-sec55');
PRAGMA foreign_keys = ON;
